[versions]
fastutil = "8.5.12"
java = "17"
joml = "1.10.5"

[libraries]
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
joml = { module = "org.joml:joml", version.ref = "joml" }

[plugins]
